import { Icon } from "@iconify/react";
import { iconData, iconRN, transformIcons } from "./icons";

const solar_bold: Partial<iconRN> = {
  settings: "settings-bold",
  widget: "widget-add-bold",
  unlock: "lock-unlocked-bold",
  lock: "lock-bold",
  habitTracker: "calendar-mark-bold",
  pin: "pin-bold",
  reset: "refresh-bold",
  checklist: "checklist-minimalistic-bold",
  bookmark: "bookmark-bold",
  edit: "pen-new-square-bold",
  delete_: "trash-bin-trash-bold",
  menu: "hamburger-menu-bold",
  show: "eye-bold",
  hide: "eye-closed-bold",
  space: "planet-2-bold",
  add: "add-square-bold",
};
export const _ri_fill: iconRN = {
  settings: "settings-4-fill",
  widget: "apps-2-add-fill",
  lock: "lock-fill",
  unlock: "lock-unlock-fill",
  habitTracker: "calendar-check-fill",
  pin: "pushpin-fill",
  search: "search-2-fill",
  reset: "refresh-fill",
  checklist: "list-check-3",
  bookmark: "bookmark-fill",
  edit: "edit-2-fill",
  delete_: "delete-bin-fill",
  menu: "menu-fill",
  show: "eye-fill",
  hide: "eye-off-fill",
  space: "rocket-2-fill",
  add: "add-circle-fill",
  note: "booklet-fill",
};
const googleMaterialDuotone = {
  settings: "twotone-settings",
  widget: "twotone-widgets",
  lock: "twotone-lock",
  unlock: "twotone-lock-open",
  habitTracker: "towtone-edit-calendar",
  pin: "towtone-push-pin",
  show: "twotone-visibility",
  hide: "twotone-visibility-off",
  search: "towtone-search",
  checklist: "towtone-checklist",
  space: "twotone-rocket-launch",
  bookmark: "twotone-bookmark",
  reset: "sharp-sync",
  edit: "twotone-edit",
  delete_: "twotone-delete",
  menu: "towtone-menu",
  add: "towtone-add",
  note: "twotone-note-alt",
};
const phDuotone = {
  note: "note-duotone",
  add: "plus-duotone",
  delete_: "trash-duotone",
  edit: "note-pencil-duotone",
  bookmark: "bookmark-simple-duotone",
  space: "planet-duotone",
  checklist: "list-plus-duotone",
  search: "magnifying-glass-duotone",
  show: "eye-duotone",
  hide: "eye-slash-duotone",
  pin: "push-pin-duotone",
  habitTracker: "calendar-dots-duotone",
  unlock: "lock-open-duotone",
  lock: "lock-duotone",
  widget: "grid-four-duotone",
  settings: "gear-duotone",
};
const mingCuteFill = {
  settings: "settings-1-fill",
  widget: "grid-fill",
  lock: "lock-fill",
  unlock: "unlock-fill",
  habitTracker: "calendar-add-fill",
  pin: "pin-fill",
  show: "eye-2-fill",
  hide: "eye-close-fill",
  search: "search-fill",
  checklist: "task-fill",
  space: "planet-fill",
  bookmark: "bookmark-fill",
  reset: "refresh-2-fill",
  edit: "edit-3-fill",
  delete_: "delete-2-fill",
  menu: "menu-fill",
  add: "add-fill",
  note: "notebook-fill",
};
const biFill = {
  search: "search",
  checklist: "card-checklist",
  settings: "gear-fill",
  widget: "grid-fill",
  lock: "lock-fill",
  unlock: "unlock-fill",
  habitTracker: "calendar-check-fill",
  pin: "pin-fill",
  show: "eye-fill",
  hide: "eye-slash-fill",
  space: "rocket-takeoff-fill",
  bookmark: "bookmark-fill",
  edit: "pencil-fill",
  delete_: "trash3-fill",
  add: "plus-circle-fill",
};
const iconaMoonFill = {
  settings: "settings-fill",
  widget: "apps-fill",
  lock: "lock-fill",
  unlock: "lock-off-fill",
  habitTracker: "calendar-add-fill",
  show: "eye-fill",
  hide: "eye-off-fill",
  search: "search-fill",
  bookmark: "bookmark-fill",
  reset: "synchronize-fill",
  edit: "edit-fill",
  delete_: "trash-fill",
  menu: "menu-burger-horizontal-fill",
  add: "sign-plus-circle-fill",
};
const ionOutline = {
  settings: "settings-outline",
  widget: "grid-outline",
  lock: "lock-closed-outline",
  unlock: "lock-open-outline",
  habitTracker: "calendar-clear-outline",
  pin: "pin-outline",
  show: "eye-outline",
  hide: "eye-off-outline",
  search: "search-outline",
  checklist: "list-outline",
  space: "planet-outline",
  bookmark: "bookmark-outline",
  reset: "sync-circle-outline",
  edit: "pencil-outline",
  delete_: "trash-outline",
  menu: "menu-outline",
  add: "add-circle-outline",
};
const teenyOutline = {
  settings: "cog-outline",
  widget: "grid-layout-outline",
  lock: "lock-outline",
  unlock: "unlock-outline",
  habitTracker: "calendar-tick-outline",
  pin: "pin-alt-outline",
  show: "eye-outline",
  hide: "eye-closed-outline",
  search: "search-outline",
  checklist: "list-layout-outline",
  space: "compass-outline",
  bookmark: "bookmark-outline",
  reset: "refresh-outline",
  edit: "edit-1-outline",
  menu: "menu-outline",
  add: "add-outline",
  note: "note-outline",
};
const clarityLine = {
  settings: "settings-line",
  widget: "grid-view-line",
  lock: "lock-line",
  unlock: "unlock-line",
  habitTracker: "calendar-line",
  pin: "pin-line",
  show: "eye-show-line",
  hide: "eye-hide-line",
  search: "search-line",
  checklist: "list-line",
  space: "compass-line",
  bookmark: "bookmark-line",
  reset: "sync-line",
  edit: "edit-line",
  delete_: "trash-line",
  menu: "menu-line",
  add: "plus-circle-line",
};
const antDesignFill = {
  settings: "tool-filled",
  widget: "appstore-add-filled",
  lock: "lock-filled",
  unlock: "unlock-filled",
  habitTracker: "calendar-filled",
  pin: "pushpin-filled",
  show: "eye-filled",
  hide: "eye-invisible-filled",
  search: "search-outlined",
  checklist: "ordered-list-outlined",
  menu: "menu-outlined",
  space: "rocket-filled",
  bookmark: "heart-filled",
  reset: "sync-outlined",
  edit: "edit-filled",
  delete_: "delete-filled",
  add: "plus-circle-filled",
};

export const ri_line = transformIcons(_ri_fill, "ri", "fill", "line");
export const ri_fill = transformIcons(_ri_fill, "ri");

export const SelectedIconPacks: Record<string, iconData> = {
  "Remix Icon Filled": ri_fill,
  "Remix Icon Line": ri_line,
  tabler: {
    ...ri_line,
    settings: "settings",
    widget: "apps",
    lock: "lock",
    unlock: "lock-open",
    habitTracker: "calendar-check",
    pin: "pin",
    search: "search",
    reset: "refresh",
    checklist: "list-check",
    bookmark: "bookmark",
    edit: "edit",
    delete_: "trash",
    menu: "menu",
    show: "eye",
    hide: "eye-off",
    space: "rocket",
    add: "square-rounded-plus",
    note: "note",
  },
  lucide: {
    ...ri_line,
    settings: "settings",
    widget: "grid-2x2-plus",
    lock: "lock",
    unlock: "lock-open",
    habitTracker: "calendar-check",
    pin: "pin",
    search: "search",
    checklist: "list-check",
    bookmark: "bookmark",
    edit: "edit",
    delete_: "trash",
    menu: "menu",
    show: "eye",
    hide: "eye-off",
    space: "rocket",
    add: "circle-plus",
    reset: "refresh-cw",
    note: "notebook",
  },
  uil: {
    ...ri_line,
    settings: "setting",
    widget: "apps",
    lock: "lock",
    habitTracker: "calendar-alt",
    search: "search",
    reset: "refresh",
    checklist: "file-check-alt",
    bookmark: "bookmark",
    edit: "edit",
    delete_: "trash",
    menu: "bars",
    show: "eye",
    hide: "eye-slash",
    space: "rocket",
    add: "plus-circle",
  },
  carbon: {
    ...ri_line,
    settings: "settings",
    widget: "grid",
    lock: "locked",
    unlock: "unlocked",
    habitTracker: "calendar",
    pin: "pin",
    search: "search",
    reset: "reset",
    checklist: "list-checked",
    bookmark: "bookmark",
    edit: "edit",
    delete_: "trash-can",
    menu: "menu",
    space: "rocket",
    add: "add-alt",
    show: "view",
    hide: "view-off",
    note: "white-paper",
  },
  hugeicons: {
    ...ri_line,
    settings: "settings-01",
    widget: "resources-add",
    lock: "circle-lock-01",
    unlock: "circle-unlock-01",
    habitTracker: "calendar-favorite-01",
    pin: "pin",
    search: "search-01",
    reset: "refresh",
    checklist: "check-list",
    bookmark: "bookmark-02",
    edit: "edit-02",
    delete_: "delete-02",
    menu: "menu-01",
    show: "view",
    hide: "view-off",
    space: "rocket",
    add: "add-square",
    note: "note-01",
  },
  iconoir: {
    ...ri_line,
    settings: "settings",
    widget: "grid-plus",
    lock: "lock",
    unlock: "lock-slash",
    habitTracker: "calendar-check",
    pin: "pin",
    show: "eye",
    hide: "eye-closed",
    search: "search",
    checklist: "task-list",
    space: "planet",
    bookmark: "bookmark",
    reset: "refresh-double",
    edit: "edit",
    delete_: "trash",
    menu: "menu",
    add: "plus-circle",
  },
  "line-md": {
    ...ri_line,
    add: "plus-circle",
    checklist: "check-list-3-filled",
    menu: "menu",
    edit: "edit",
    show: "watch-loop",
    hide: "watch-off-loop",
    search: "search",
    settings: "cog-loop",
    space: "compass-loop",
    habitTracker: "calendar",
    bookmark: "star",
    reset: "backup-restore",
    delete_: "close-circle-filled",
    widget: <Icon icon="svg-spinners:blocks-scale" />,
  },
  majesticons: {
    ...ri_fill,
    note: "note-text",
    delete_: "delete-bin",
    edit: "edit-pen-2",
    bookmark: "bookmark",
    menu: "menu",
    add: "plus",
    space: "planet-ring-2",
    checklist: "radio-list",
    search: "search",
    show: "eye",
    hide: "eye-off",
    pin: "pin",
    habitTracker: "calendar",
    lock: "lock",
    unlock: "unlock-open",
    settings: "settings-cog",
  },
  "gravity-ui": {
    ...ri_line,
    settings: "gear",
    lock: "lock",
    unlock: "lock-open",
    habitTracker: "calendar",
    pin: "pin",
    show: "eye",
    hide: "eye-slash",
    checklist: "list-check",
    space: "rocket",
    bookmark: "bookmark",
    edit: "pencil",
    delete_: "trash-bin",
    add: "plus",
  },
  octicon: {
    ...ri_line,
    settings: "gear-16",
    widget: "apps-16",
    lock: "lock-16",
    unlock: "unlock-16",
    habitTracker: "calendar-16",
    pin: "pin-16",
    show: "eye-16",
    hide: "eye-closed-16",
    search: "search-16",
    checklist: "tasklist-16",
    space: "rocket-16",
    bookmark: "bookmark-16",
    reset: "sync-16",
    edit: "credit-card-16",
    delete_: "trash-16",
    add: "plus-16",
    note: "note-16",
  },
  cil: {
    ...ri_line,
    settings: "settings",
    lock: "lock-locked",
    unlock: "lock-unlocked",
    habitTracker: "calendar-check",
    pin: "pin",
    search: "search",
    checklist: "task",
    space: "compass",
    bookmark: "bookmark",
    reset: "sync",
    edit: "pencil",
    delete_: "trash",
    menu: "menu",
    add: "plus",
    note: "notes",
  },
  "Solar Bold": { ...ri_fill, ...transformIcons(solar_bold, "solar") },
  "Solar Bold Duotone": {
    ...ri_fill,
    ...transformIcons(solar_bold, "solar", "bold", "bold-duotone"),
  },
  "Solar Line Duotone": {
    ...ri_line,
    ...transformIcons(solar_bold, "solar", "bold", "line-duotone"),
  },
  "Solar Broken": {
    ...ri_line,
    ...transformIcons(solar_bold, "solar", "bold", "broken"),
  },
  "Solar Line": {
    ...ri_line,
    ...transformIcons(solar_bold, "solar", "bold", "linear"),
  },
  "Google Material Two Tone": transformIcons(googleMaterialDuotone, "ic"),
  "Google Material Baseline": transformIcons(googleMaterialDuotone, "ic", "towtone", "baseline"),
  "Google Material Rounded": transformIcons(googleMaterialDuotone, "ic", "twotone", "round"),
  "Google Material Sharp": transformIcons(googleMaterialDuotone, "ic", "towtone", "sharp"),
  Phosphor: { ...ri_line, ...transformIcons(phDuotone, "ph", "-duotone", "") },
  "Phosphor Fill": {
    ...ri_fill,
    ...transformIcons(phDuotone, "ph", "duotone", "fill"),
  },
  "Phosphor Bold": {
    ...ri_fill,
    ...transformIcons(phDuotone, "ph", "duotone", "bold"),
  },
  "Phosphor Light": {
    ...ri_line,
    ...transformIcons(phDuotone, "ph", "duotone", "light"),
  },
  "Phosphor Thin": {
    ...ri_line,
    ...transformIcons(phDuotone, "ph", "duotone", "thin"),
  },
  "Phosphor Duotone": { ...ri_line, ...transformIcons(phDuotone, "ph") },
  "MingCute Fill": { ...ri_fill, ...transformIcons(mingCuteFill, "mingcute") },
  "MingCute Line": {
    ...ri_line,
    ...transformIcons(mingCuteFill, "mingcute", "fill", "line"),
  },
  "Bootstrap Line": {
    ...ri_line,
    ...transformIcons(biFill, "bi", "-fill", ""),
  },
  "Bootstrap Fill": { ...ri_fill, ...transformIcons(biFill, "bi") },
  "Icona Moon Fill": {
    ...ri_fill,
    ...transformIcons(iconaMoonFill, "iconamoon"),
  },
  "Icona Moon Bold": {
    ...ri_line,
    ...transformIcons(iconaMoonFill, "iconamoon", "fill", "bold"),
  },
  "Icona Moon Duotone": {
    ...ri_line,
    ...transformIcons(iconaMoonFill, "iconamoon", "fill", "duotone"),
  },
  "Icona Moon Regular": {
    ...ri_line,
    ...transformIcons(iconaMoonFill, "iconamoon", "-fill", ""),
  },
  "Icona Moon thin": {
    ...ri_line,
    ...transformIcons(iconaMoonFill, "iconamoon", "fill", "thin"),
  },
  "Ionicons Outline": { ...ri_line, ...transformIcons(ionOutline, "ion") },
  "Ionicons Regular": {
    ...ri_fill,
    ...transformIcons(ionOutline, "ion", "-outline", ""),
  },
  "Ionicons Sharp": {
    ...ri_fill,
    ...transformIcons(ionOutline, "ion", "-outline", "-sharp"),
  },
  "Teeny Icons Outline": {
    ...ri_line,
    ...transformIcons(teenyOutline, "teenyicons"),
  },
  "Teeny Icons Solid": {
    ...ri_line,
    ...transformIcons(teenyOutline, "teenyicons", "outline", "solid"),
  },
  "Clarity Solid": {
    ...ri_fill,
    ...transformIcons(clarityLine, "clarity", "line", "solid"),
  },
  "Clarity Line": { ...ri_fill, ...transformIcons(clarityLine, "clarity") },
  "Ant Design Fill": {
    ...ri_fill,
    ...transformIcons(antDesignFill, "ant-design"),
  },
  "Ant Design Outlined": {
    ...ri_line,
    ...transformIcons(antDesignFill, "ant-design", "filled", "outlined"),
  },
};
